<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms and Condition</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="../css/terms.css?v=1.0">
</head>
<body>

  <div class="terms-container">
        
        <div class="terms-header">
            <a href="signup.php">
                <i class="fa-solid fa-arrow-left"></i> 
            </a>
          <h1>Terms and Conditions</h1>  
           <a href="signup.php">
                <i class="fa-solid fa-x"></i>
            </a>
        </div>
        
        <div class="terms-content">
           
            <div class="terms-text">
                <h3>1. About Terms and Conditions</h3>

<p>These terms and conditions (referred to as "Terms" or "Agreement") form a binding and legal contract between you and Akasi Healthcare Inc. ("Akasi," "we," or "us") and apply to your use of the Akasi website, mobile applications, and any related services ("Services") we operate or reference. As used in this Agreement, "you" means any visitor, user, or other person who accesses our Services, whether or not such person registered for a Akasi Account.</p>

<p>Specific Services within Akasi may require additional terms, which you will be prompted to review before using those services and are considered part of this Agreement. For the purposes of these Terms, "Services" broadly include features like scheduling pages, virtual walk-in appointments, and video services for telehealth consultations.</p>

<p>By accessing or using the Services, you agree to comply with these Terms. If you do not accept these terms, please discontinue use of the Services.</p>

<p>If your use of the Services is terminated, these Terms will continue to apply to your prior use and obligations under the Agreement, including indemnification responsibilities.</p>

<p>Akasi's Privacy Policy governs how we collect and use personal data connected to the Services.</p>

<p>As we work to improve our Services, we may need to update our Terms. We reserve the right to change these Terms at any time. We will notify you by updating this page, sending an email, or other suitable means.</p>

<p>Please read this Agreement carefully. By your use of the Services, you acknowledge and agree that:</p>

<p>You have read and understand these Terms and Conditions,
You accept and agree to be bound by this Agreement, making it as enforceable as a signed contract between you (or your entity) and Akasi, and
If you are acting on behalf of an entity, you have the authority to bind that entity to this Agreement.
If you or your entity do not agree to these Terms, you are free to discontinue use of the Services. Do not use the Services if you are unwilling or unable to be bound by these Terms.</p>

<h3>2. License</h3>
<p>Akasi grants you a limited, non-exclusive, revocable, and non-transferable license to use its services, as outlined in these Terms. While certain parts of the services can be accessed without creating a Akasi Account, full access requires an account (a "Akasi Account"), where you will provide basic personal information. By providing this information, you authorize Akasi to use and share it in accordance with our Privacy Policy.</p>

<h3>3. Materials</h3>
<p>Akasi may present various types of content, such as text, images, videos, and guidance materials through our Services (collectively, "Site Materials" or "Materials"), some of which may be generated by healthcare professionals. Site Materials are provided solely for informational purposes to help you make healthcare decisions, but it does not establish a patient-provider relationship or serve as medical advice, diagnosis, or treatment. "Healthcare Providers" refers to doctors, dentists, other healthcare specialists, professionals, providers, organizations, or their agents and affiliates collectively.</p>

<p>We aim to provide accurate and helpful Materials, but make no guarantees, expressed or implied, about its accuracy, completeness, or reliability. Materials within the Services, including professional qualifications, expertise, or insurance details, are intended only to help you choose Healthcare Providers.</p>

<p>Materials regarding Healthcare Providers and their practices is provided for general reference and may come from the Healthcare Provider, their staff, or various data sources. Although we aim to confirm and update this information, it may be outdated, incomplete, or inaccurate. Akasi does not endorse or verify the qualifications of any Healthcare Provider.</p>

<p>Insurance-related Materials, including coverage details and benefits, are intended solely for convenience. This information may be based on Personal Data you provide, combined with data from Healthcare Providers, insurance providers, or third-party sources. Since insurance information can frequently change, you are responsible for providing accurate insurance-related data and verifying its accuracy. Akasi strives for accuracy but is not liable for any inaccuracies or outdated information.</p>

<p>Any decisions made based on Site Materials are solely your responsibility, and under no circumstances will we be liable to you or others for any decisions you make in reliance on such Material.</p>

<p>We recommend independently verifying any relevant Materials with additional sources, such as the Healthcare Provider's office, related medical associations, your state medical boards, and the proper licensing or certification authorities to confirm credentials and qualifications.</p>

<p>All Materials on our Services are owned by us or our licensors and are protected by copyright, trademark, patent, and trade secret laws, as well as other proprietary rights and international treaties. You acknowledge that the Services and any underlying technology or software used in connection with them contain proprietary information belonging to Akasi. We allow you to use the Materials solely for personal, non-commercial purposes, without transferring any intellectual property rights.</p>

<p>You may print, download, and store information from the Services for personal use, but you may not copy, distribute, republish (unless explicitly allowed), sell, or otherwise exploit the Materials or Services for commercial purposes. Akasi and its suppliers retain all rights in the Services that are not explicitly granted here.</p>

<h3>4. No Medical Advice</h3>

<p>We do not offer medical advice. Any information you obtain from Akasi or its affiliates, including Materials and/or content on our website, emails, social media channels, or other communications, is for informational and scheduling purposes only and should not replace professional medical advice, diagnosis, or treatment.</p>

<p>PLEASE DO NOT USE OUR SERVICES FOR URGENT MEDICAL NEEDS. If you are experiencing a medical or mental health emergency, call 911 or seek immediate help from a healthcare professional. Your use of the Services is solely at your own risk and should not be considered medical practice or advice.</p>

<h3>5. No Recommendations</h3>
<p>Akasi is not a referral service and does not refer, recommend, or endorse any Healthcare Provider, individual, entity, test, procedure, opinion, or other information that may appear through the Materials and/or Services.</p>
<p>Akasi does not employ Healthcare Providers, nor does it guarantee their qualifications or the quality of their services. Akasi is not liable for the accuracy of Healthcare Provider information and does not ensure that services meet any specific quality standard. Akasi does not control the actions of Healthcare Providers, and they are not our employees.</p>

<h3>6. No Doctor-Patient Relationship</h3>
<p>The Services and Materials provided by Akasi are not a substitute for healthcare, and no doctor-patient relationship is established through your use of the Services or Materials. This holds whether the Materials are provided via the Services, or through any other communications from Akasi including the blog, social channels, emails, text messages, or any assistance we may offer in helping you find a Healthcare Provider.</p>
<p>Akasi encourages Healthcare Providers to use the Services responsibly; however, we cannot guarantee the availability of any specific Healthcare Provider or be liable for any cancellations or unfulfilled appointments, nor any resulting issues arising from your use of the Services.</p>
<p>Akasi verifies —in a limited capacity —that Healthcare Providers hold active licenses, certifications, or registrations legally required to practice their listed specialties. Akasi may also exclude any Healthcare Providers from the Services if they engage in unprofessional conduct.</p>
<p>You are solely responsible for selecting your own Healthcare Provider, including determining whether a particular provider is suitable for your healthcare needs based on factors such as specialty, experience, qualifications, licenses, and other relevant considerations that may affect your care.</p>
<p>Akasi's list of Healthcare Providers is not comprehensive; Healthcare Providers can choose to participate, control their listed availability, and may have additional openings if contacted directly.</p>

<h3>7. Medical Information</h3>
<p>You may enter medical information into the Services when booking an appointment. This information is shared with your chosen Healthcare Provider solely for booking and scheduling purposes. Once you request an appointment, the Healthcare Provider will have access to this information for as long as you continue using the Services. You or someone you authorized are responsible for reviewing and confirming the accuracy of this information at the time of your appointment. Akasi will use and manage this information as outlined in its Privacy Policy.</p>

<h3>8. Your Responsibilities</h3>
<p>8.1 Akasi Account Security and Creating an Account</p>
<p>To access our Services to the fullest intended extent, you must create a Akasi Account and provide an email address and/or mobile number and password "Credentials" as part of the registration process. Keep these Credentials confidential, and do not share them. If you suspect any unauthorized use, notify us immediately. We reserve the right to modify or delete any password at our discretion.</p>
<p>By creating a Akasi Account, you confirm that (a) you are at least 18 years old, (b) you are using your real identity, (c) the information you provide is accurate, and (d) you will promptly update your information as needed.</p>
<p>By logging in with your password, you confirm you are authorized to use it and assume responsibility for keeping it secure, along with all activities under it.</p>
<p>8.2 General Responsibilities</p>
<p>Creating a Akasi Account and/or accessing our Servies is free; however, any healthcare services you receive remain your financial responsibility. Charges for medical services from Healthcare Providers are your obligation alone.</p>
<p>Any transaction-related disputes are solely between you and your Healthcare Provider and must be resolved directly with your Healthcare Provider.</p>
<p>You are also responsible for providing accurate information, such as insurance details, and understand that some Services may be limited through Akasi or your Healthcare Provider due to your insurance participation among other factors.</p>
<p>Any use of your Credentials or the Services is your responsibility, including any actions taken by others to whom you have given access. The Services are for lawful, non-commercial use only. If your jurisdiction has restrictions, compliance is up to you.</p>
<p>You are strictly prohibited from using the Services in any way that might harm, disable, overload, or compromise our servers, networks, or the Services' functionality, or otherwise interfere with any other party's ability to use and enjoy the Services. Unauthorized access or attempts to exceed permitted access to any Services, user accounts, systems, or networks are also forbidden. Furthermore, you may not collect, index, or otherwise gather any Materials from the Services, directly or indirectly, for any purpose.</p>
<p>We retain the right to take legal measures and use technological solutions to prevent violations and ensure compliance with these Terms of Use.</p>
<p>8.3 Healthcare Providers and Workers in the Medical or Healthcare Industries</p>
<p>If you are a Healthcare Provider or an entity in healthcare or medical industries, you acknowledge that:</p>
<p>Accessing price, availability, or other details through the Services is only for personal, non-commercial use.
The Services are not to be used to coordinate pricing, limit output, price fixing, or allocate customers or markets.
Anti-competitive, deceptive, or unfair practices, such as fraudulent bookings or review manipulation, are strictly prohibited.</p>
<p>8.4 Restricted Uses</p>
<p>You agree to use Akasi's Platform and Services only for lawful purposes and in accordance with these Terms and our Community Standards. Without limiting any of the following, you shall not, nor shall you allow or enable any third party to:</p>
<p>1. Prohibited Content and Behavior</p>
<p>Violate any applicable laws or regulations, including privacy laws and export regulations.
Use the Platform or Services to exploit, harm, or attempt to harm minors in any way.
Post or transmit unlawful, threatening, libelous, defamatory, obscene, scandalous, inflammatory, or otherwise inappropriate materials.
Engage in any conduct that restricts or inhibits anyone's use or enjoyment of the Platform, or that could harm Akasi or its users.</p>
<p>2. Unauthorized Access and Security Violations</p>
<p>Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the Platform, the server on which it is hosted, or any server, computer, or database connected to it.
Jeopardize the security of your Akasi Account Credentials or attempt to obtain security information from other users.
Attempt to access or retrieve Materials for purposes of creating a database or competing service related to healthcare or Healthcare Providers.
Use automated means (such as bots or spiders) to access, scrape, retrieve, or index any part of the Platform or Services.</p>
<p>3. Intellectual Property Infringement</p>
<p>Copy, modify, adapt, translate, or reverse engineer any Materials or part of the Platform, including its underlying code, materials, or Services.
Remove or alter any copyright, trademark, or proprietary notices on the Platform, Services, or Materials.</p>
<p>4. Misuse of Services and Fraudulent Activity</p>
<p>Fraudulently or intentionally misuse the Services, including booking appointments you do not intend to keep or submitting information under false pretenses.
Use contact information from users or Healthcare Providers to send unsolicited communications or SPAM.
Create user accounts, book appointments, or submit information under false or misleading identities.</p>
<p>5. Disruptive Technologies and Harmful Interference</p>
<p>Use any device, software, or routine that interferes with the proper working of the Platform.
Introduce any viruses, worms, logic bombs, or other harmful materials.
Attack the Platform via a denial-of-service (DoS) or distributed denial-of-service (DDoS) attack.</p>
<p>6. Improper Data Collection and Use</p>
<p>Collect or store personal data about other users for prohibited purposes.
Conduct web scraping or use other means to gather data from the Platform.</p>

<h3>9. User Disputes</h3>
<p>Akasi has no obligation to mediate disputes between users or with Healthcare Providers. By using the Services, you release Akasi, its employees, and all affiliates from liability for any claims or damages related to such disputes.</p>

<h3>10. Telemedicine Services</h3>
<p>You may access telemedicine through the Services, including Akasi's video platform or third-party virtual care options ("Video Services"). Akasi is not a healthcare provider, insurer, or prescription fulfillment provider; our role is limited to making telehealth information available and connecting you with telemedicine offered by Healthcare Providers. Akasi is independent of these Healthcare Providers, and we do not control or take responsibility for the content, availability, quality, legality, or security of Video Services, whether from Akasi or third-party providers. We advise reviewing the terms and privacy policies of any third-party providers you use. By using Video Services, you agree that Akasi is not liable for any issues arising from your use of these services.</p>

<h3>11. Third-Party Links and Services</h3>
<p>11.1 Links to Other Websites</p>
<p>The Services may include links to external websites solely for your convenience. Akasi does not endorse these sites or their content, products, or services, and is not responsible for their accuracy, legality, or any materials they may contain. Any interactions or transactions with third-party websites or services, including payment or delivery, are strictly between you and those parties. Akasi disclaims any responsibility or liability arising from such dealings.</p>
<p>Healthcare Providers may use our Custom Messages feature to add information to standard appointment communications, including but not limited to links to third-party forms or information requests. Akasi is not responsible for any links or content shared by Healthcare Providers in these communications. Any information you provide through third-party links is solely between you and the Healthcare Provider, and Akasi does not receive, review, store, or assume any responsibility for that information, including how it is used, stored, or shared by the Healthcare Providers. Akasi is not liable for any harm, damages, or other consequences resulting from your access to or use of third-party links or forms sent by Healthcare Providers, nor for any additional information or content providers may include in their communications.</p>
<p>Akasi is under no obligation to clarify whether portions of communications you receive contain content created or added by Healthcare Providers. By opting in to receive these communications, you acknowledge and agree that they may include information provided by Healthcare Providers, without any requirement for Akasi to specify or disclose the source or author of that information.</p>
<p>11.2 Third-Party Software</p>
<p>Our Services may incorporate third-party software, including open-source components. Your use of this software is subject to additional terms set by the respective providers, which may include attribution and disclaimers that Akasi provides where applicable.</p>
<p>11.3 Application Stores</p>
<p>Our mobile application's availability depends on third-party app stores (e.g., Apple App Store, Google Play) (each, an "Application Provider"). By downloading the mobile application, you agree to comply with each Application Provider's terms, which may govern alongside these Terms of Use. In the event of any conflict between these Terms and those of the Application Provider, the more restrictive terms apply.</p>
<p>If you are using the Services via an application (an "Application") through an Application Provider, you acknowledge that:</p>
<p>1. Akasi is solely responsible for the application, not the Application Provider.</p>
<p>2. The application is licensed to you on a limited, non-transferable, and non-sublicensable basis for use with the Services.</p>
<p>3. The Application Provider has no responsibility for support, warranty, or claims related to the application.</p>
<p>4. You will comply with all third-party terms affecting your use of the application.</p>
<p>5. The Application Provider and its subsidiaries are third-party beneficiaries of these Terms of Use with respect to the application.</p>
<p>If a third party claims that the application infringes their intellectual property rights, Akasi, not the Application Provider, will handle the matter.</p>

<h3>12. Plans and Payment</h3>
<p>Healthcare Providers joining Akasi must select a plan ("Subscription Plan" or "Plan") to access the Services. We may offer a Plan that provides limited access to portions of the Services free of charge (a "Free Plan"), but we do not guarantee the indefinite availability of any Free Plan. Healthcare Providers may also choose to subscribe to a Plan that includes access to additional features not available in the Free Plan (a "Paid Plan"). The "Subscription Period" refers to the time between the Plan's start date and its end/renewal date. Paid Plans can be subscribed to on a monthly basis ("Monthly Plan") with a Subscription Period of 30 days, or on an annual basis ("Annual Plan") with a Subscription Period of 365 days. Currently, Akasi does not charge patients.</p>
<p>Current Plans are not guaranteed to remain unchanged. Akasi reserves the right to modify the number, types, features, and pricing of available Plans at its discretion, and may discontinue any Plan or feature at any time without prior notice.</p>
<p>Providers opting for Paid Plans are charged upfront at the start of the Subscription Period. Payment information is processed in accordance with our Privacy Policy, and Akasi or its payment partners may apply a transaction fee. Any payment terms set during registration or while using the Services are part of these Terms. If third-party payment processing partners are involved, Healthcare Providers may need to accept their terms as well. Akasi's current payment processor is Stripe, please refer to their terms here.</p>
<p>Healthcare Providers can switch from Monthly Plans to Annual Plans, with the Annual Plan starting on the date of the current Monthly Plan and extending for 365 days; Healthcare Providers must cover the price difference at the time of switching Plans. Providers on Annual Plans may switch to a Monthly Plan; however, this change will take effect only after the current Subscription Period of their Annual Plan ends, at which point the Monthly Plan associated with their current Paid Plan will begin and be billed at the applicable rate.</p>
<p>If certain Plans are discontinued, Healthcare Providers will be prompted to select a new Plan once their current Plan's Subscription Period ends. Akasi is not obligated to maintain a Plan's existing feature set indefinitely, and Healthcare Providers subscribed to a discontinued Paid Plan who do not select a new Paid Plan at renewal will be automatically downgraded to the Free Plan after a decided grace period, subject to change at our discretion. Akasi is not liable for any losses or damages resulting from such downgrades.</p>
<p>Payments may include transaction processing fees, and additional charges may apply for separate services. By using the Services, you agree to:</p>
<p>Pay the designated fees for Services,
Permit Akasi or its payment partner to process your payment,
Acknowledge that Akasi is not liable for any additional charges, and
Adhere to terms from payment partners.</p>
<p>Healthcare Providers are responsible for maintaining accurate and current billing information to avoid processing issues. If Akasi cannot process a renewal payment, the Healthcare Provider's account will be downgraded to the Free Plan after a grace period, which may be adjusted at our discretion, resulting in the loss of premium features. Akasi is not responsible for material damages or any losses stemming from such downgrades or terminations due to unprofessional conduct, for which refunds will not be issued.</p>
<p>Akasi is not responsible for any error by or other acts of the payment processor. Akasi and its payment partners are not liable if a transaction fails due to incomplete payment information, insufficient funds, inactive payment cards, or suspected unauthorized activity.</p>
<h3>13. User Content</h3>
<p>Through Akasi's Services, you may share feedback on your experiences with Healthcare Providers, ask questions, and engage in interactive community features ("Submissions"). When providing Submissions, please ensure it is respectful, truthful, and concise, without including personally identifiable information for yourself or others.</p>
<p>Akasi reserves the right to publish, edit, or remove your Submissions at our discretion, though we are not liable for delays or omissions in posting or removing content. Please note that content posted by others reflects solely the opinions of those users and should not be viewed as verified by Akasi.</p>
<p>Guidelines for Submissions:</p>
<p>You bear full responsibility for any content you submit through the Platform.
Do not post any content that infringes upon intellectual property, privacy, or publicity rights of others.
Avoid posting content that could imply endorsement by Akasi or promotes unlawful or inappropriate behavior, including abusive, hateful, defamatory, or obscene material.
Ensure your content genuinely reflects your experiences and beliefs.
Prohibited content includes:</p>
<p>False, misleading, or deceptive information.
Harassment or encouragement of harm to any individual or entity.
Unsolicited bulk messages or "spam."
Violations of intellectual property rights, privacy, or other legal protections.
Any unlawful, discriminatory, violent, or sexually explicit material.</p>
<p>Akasi may review and remove any content that violates these standards, but we do not verify the accuracy of Submissions, which remains the responsibility of the original poster. We handle all Submissions in accordance with our Privacy Policy.</p>
<p>By submitting Submissions, you grant Akasi and its affiliates a perpetual, worldwide, royalty-free license to use, edit, distribute, and display this content on any platform. You confirm that you have the right to grant this permission without infringing on third-party rights, including privacy or intellectual property. Akasi may modify your content to meet technical requirements across various platforms, with your agreement to these adjustments.</p>
<p>We also welcome suggestions and feedback for improving Akasi's Services ("Feedback"). By submitting Feedback, you grant Akasi a royalty-free license to use this information for any purpose, without compensation.</p>

<h3>14. Disclaimers</h3>
<p>ALL MATERIALS AND SERVICES PROVIDED HERE ARE OFFERED ON AN "AS IS" AND "AS AVAILABLE" BASIS AND ARE INTENDED FOR INFORMATIONAL PURPOSES ONLY. WHILE WE STRIVE TO DELIVER ACCURATE, CURRENT INFORMATION, THE MATERIALS MAY INCLUDE TECHNICAL OR TYPOGRAPHICAL ERRORS OR INACCURACIES AND MAY BE UPDATED OR MODIFIED WITHOUT NOTICE.</p>
<p>TO THE FULLEST EXTENT ALLOWED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO: (A) WARRANTIES CONCERNING THE AVAILABILITY, ACCURACY, RELIABILITY, COMPLETENESS, TIMELINESS, QUALITY, PERFORMANCE, OR SUITABILITY OF THIS SITE, ITS MATERIALS, OR ANY PRODUCTS, SERVICES, OR RESULTS ACCESSED THROUGH THIS SITE; AND (B) ANY IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. WE DO NOT GUARANTEE THAT THIS SITE OR ANY MATERIALS WILL HELP YOU FIND A SUITABLE HEALTHCARE PROVIDER OR SERVE ANY PARTICULAR PURPOSE. WE MAKE NO REPRESENTATION THAT THIS SITE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, NOR DO WE GUARANTEE THAT ANY DEFECTS WILL BE CORRECTED. YOU EXPRESSLY AGREE THAT YOUR USE OF THIS SITE AND ITS MATERIALS IS ENTIRELY AT YOUR OWN RISK.</p>
<p>WE ALSO EXPRESSLY DISCLAIM RESPONSIBILITY AND LIABILITY FOR ANY AGREEMENTS YOU MAY ENTER INTO WITH HEALTHCARE PROVIDERS OR THIRD PARTIES WHO OFFER PRODUCTS OR SERVICES ON OR THROUGH THIS SITE. ANY CLAIMS RELATED TO SUCH AGREEMENTS, PRODUCTS, OR SERVICES MUST BE ADDRESSED SOLELY WITH THOSE PROVIDERS OR THIRD PARTIES.</p>

<h3>15. Limitation of Liability</h3>
<p>NEITHER WE NOR OUR AFFILIATES WILL BE LIABLE FOR ANY DAMAGES ARISING FROM YOUR USE OF OR RELIANCE ON THIS SITE, ITS MATERIALS, OR ANY PRODUCTS OR SERVICES ACCESSED THROUGH THIS SITE. IN THE EVENT OF ANY ISSUE WITH THIS SITE, ITS MATERIALS, OR ANY PRODUCTS OR SERVICES OBTAINED HERE, YOUR SOLE REMEDY IS TO CEASE USING THE ITEM(S) IN QUESTION.</p>
<p>UNDER NO CIRCUMSTANCES WILL WE OR OUR AFFILIATES, INCLUDING OUR OR THEIR RESPECTIVE DIRECTORS, OFFICERS, SHAREHOLDERS, PARTNERS, EMPLOYEES, AGENTS, REPRESENTATIVES, OR SUCCESSORS, BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING LOST PROFITS OR DAMAGES DUE TO INCONVENIENCE, DELAY, OR LOSS OF USE) ARISING FROM USE OF THIS SITE, ITS MATERIALS, OR ANY ARRANGEMENTS OR PRODUCTS/SERVICES MADE OR OBTAINED THROUGH THIS SITE, EVEN IF WE HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGES. IN STATES THAT DO NOT ALLOW LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THIS LIMITATION MAY NOT APPLY TO YOU.</p>

<h3>16. TERMINATION</h3>
<p>We reserve the right to immediately terminate, suspend, or deactivate your Akasi Account, at our sole discretion and without prior notice, if you or anyone using your credentials has violated this Agreement or other terms posted through the Services. Additionally, your account may be terminated, suspended, or deactivated for other reasons, including prolonged inactivity. Akasi will not be liable for any consequences of termination, suspension, or deactivation, and you agree not to use the Services following such action (except if deactivation is solely due to inactivity, allowing you to create a new account). Termination may lead to the deletion of any content associated with your account.</p>
<p>Terms intended to survive termination will remain effective following termination or expiration of this Agreement. Akasi also reserves the right to investigate any violations of these Terms or applicable laws and may take legal action, including removing content, terminating accounts, or blocking access where necessary.</p>

<h3>17. Indemnity</h3>
<p>You agree to defend, indemnify, and hold Akasi, our affiliates, and each of our respective directors, officers, shareholders, partners, employees, agents, representatives, and successors harmless from any and all claims, actions, damages, injuries, liabilities, losses, costs, and expenses (including reasonable attorneys' fees and litigation expenses) arising out of or related to (a) your use of the Services, any Materials, or any products or services obtained through the Services; (b) any arrangements you make based on information acquired through the Services; or (c) any breach by you of this Agreement.</p>
<p>If you are a California resident, you waive California Civil Code Section 1542, which states:</p>
<p>"A general release does not extend to claims which the creditor does not know or suspect to exist in his or her favor at the time of executing the release, which if known by him or her must have materially affected his or her settlement with the debtor."</p>
<p>If you are not a California resident, you waive rights under any similar laws or principles in your jurisdiction of residence.</p>

<h3>18. Arbitration Agreement</h3>
<p>We hope to resolve any concerns you have with Akasi directly via binding, individual arbitration.</p>
<p>If a dispute arises, please be aware of the following terms for resolution, including arbitration. These terms require arbitration for certain disputes and limit how you may seek relief from Akasi. Akasi's officers, directors, employees, contractors, and affiliates are third-party beneficiaries to these Terms and have the right to enforce them if necessary.</p>
<p>18.1 Arbitration and Venue</p>
<p>All disputes related to these Terms will be settled by binding arbitration in the state of New Jersey. BOTH PARTIES AGREE TO WAIVE THE RIGHT TO A TRIAL BY JURY. Arbitration will be the exclusive method for resolving disputes arising out of or relating to the Services, except for qualifying claims which may be brought in small claims court in New Jersey.</p>
<p>18.2 Waiver of Class Action</p>
<p>ALL CLAIMS OR DISPUTES COVERED UNDER THIS AGREEMENT MUST BE BROUGHT ON AN INDIVIDUAL BASIS ONLY. You waive the right to participate in any class action or representative proceeding against Akasi.</p>
<p>18.3 Exclusive Court Venue</p>
<p>If arbitration is inapplicable, or for injunctive relief or small claims, you agree that any legal proceedings will be exclusively in the state or federal courts in New Jersey.</p>
<p>18.4 Severability</p>
<p>If the class action waiver is found unenforceable, the rest of this Arbitration Agreement is void. This agreement will survive termination of your relationship with Akasi.</p>
<p>18.5 Opt-Out Option</p>
<p>You may opt out of this Arbitration Agreement by sending a written notice of your decision to opt out to the following address: Akasi, Attn: Legal, 1 Kalisa Way, Suite 101, Paramus, NJ 07652. This notice must be postmarked within thirty (30) days of your acceptance of these Terms. Your notice must include (i) your name and residence address, (ii) the email address and/or telephone number associated with your account, and (iii) a clear statement that you wish to opt out of this Arbitration</p>

<h3>19. Miscellaneous</h3>
<p>19.1 Notice and Procedure for Claims of Copyright and Intellectual Property Infringement</p>
<p>If you believe that any content, materials, or other information displayed on or provided through the Akasi Platform infringes your copyright, please submit a notification in accordance with the Digital Millennium Copyright Act (DMCA). You may contact Akasi at legal@akasi.com with the subject line "DMCA Notice." See 17 U.S.C. § 512 for more details. For the notice to be effective, it must include:</p>
<p>1. Your electronic or physical signature, if you are authorized to act on behalf of the copyright owner;</p>
<p>2. A description of the copyrighted work claimed to be infringed;</p>
<p>3. Information sufficient to locate the allegedly infringing material on Akasi's Platform;</p>
<p>4. Contact details where Akasi can reach you, including address, phone number, and email;</p>
<p>5. A statement confirming your good faith belief that the use of the material is unauthorized; and</p>
<p>6. A statement affirming that the information provided is accurate and, under penalty of perjury, that you are authorized to act on behalf of the copyright owner.</p>
<p>Mail correspondence can be directed to Akasi at 1 Kalisa Way, Suite 101, Paramus, NJ 07652.</p>
<p>19.2 Counter-Notice for Removed Material</p>
<p>If you believe material you posted was wrongly removed or that you have authorization from the copyright owner to use it, you may send a counter-notice to Akasi containing:</p>
<p>1. Your physical or electronic signature;</p>
<p>2. Identification of the material removed and its location prior to removal;</p>
<p>3. A statement under penalty of perjury that the removal was due to error or misidentification; and</p>
<p>4. Your contact information, including a consent to the jurisdiction of a federal court in New Jersey and agreement to accept service of process from the notifier of the alleged infringement.</p>
<p>19.3 Claims of Other Intellectual Property Infringement</p>
<p>If you believe your intellectual property rights (e.g., trademark) have been infringed, you may submit a notice to Akasi at legal@akasi.com with the following:</p>
<p>1. Identification of the intellectual property right claimed to be infringed;</p>
<p>2. Information sufficient to locate the allegedly infringing material on the Akasi Platform;</p>
<p>3. Your contact information, including address, phone, and a valid email;</p>
<p>4. A statement of good faith belief that the material's use is unauthorized.</p>
<p>Akasi may provide a copy of your request to the user who posted the material. Akasi may, at its sole discretion, remove or disable access to infringing content and terminate the accounts of repeat infringers.</p>
<p>19.4 Phone and Text Communications</p>
<p>Transactional Messages: By providing your mobile number, you consent to receive texts and calls from Akasi for operational and informational purposes, like appointment reminders. Message rates may apply, and you can reply STOP to cancel.
Marketing Messages: By opting in, you agree to receive marketing texts or calls about Akasi's offerings. Consent is not required for purchases, and you can reply STOP to cancel.
Representations & Indemnity: You confirm the phone number you provided is accurate and indemnify Akasi against claims related to unauthorized or outdated phone numbers you provided.
Participation Requirements: You need a capable mobile device, a participating carrier, and text messaging service. Message rates depend on your carrier's terms.
Opt-Out: Opt out anytime by replying STOP to messages or updating settings. Final confirmation texts may be sent after opting out.
Updating Information: Keep your contact information current to ensure timely notifications.</p>
<p>19.5 Limitation of Claims</p>
<p>Any claim related to this Agreement must be filed within one year; otherwise, it is permanently barred.</p>
<p>19.6 Severability</p>
<p>If any part of this Agreement is found invalid or unenforceable, the remaining sections stay effective. Invalid provisions will be replaced with ones that closely reflect the original intent while remaining enforceable.</p>
<p>19.7 Governing Law and Language</p>
<p>This Agreement follows the Federal Arbitration Act, applicable federal law, and New Jersey law without reference to conflicts of law. Only the English version of this Agreement is binding.</p>
<p>19.8 Entire Agreement and Waiver</p>
<p>This Agreement, alongside referenced policies, constitutes the full agreement between you and Akasi. Failure to enforce a right does not mean waiver of future rights.</p>
<p>19.9 Headings</p>
<p>Section headings are for convenience only and do not impact the interpretation of the Terms.</p>
<p>19.10 Assignment</p>
<p>Akasi can assign this Agreement to affiliates or as part of a business transfer. You may not assign it.</p>
<strong>19.11 Eligibility</strong>
<p>You must be 18 or older, or of legal contracting age in your jurisdiction, 
    to use Akasi independently. Users 13-18 can only use the Services under parent or
     guardian supervision. By using the Services for a minor, you confirm you are their
      legal guardian. Use outside the U.S. is at the user's risk and not encouraged by 
      Akasi. Compliance with applicable laws is the user's responsibility.</p>
   
   
   
    </div>
        </div>
        <div class="terms-footer">
            <div class="button-container">
                <button type="button" class="accept-btn">
                    <span>Accept</span>
                </button>
               
            </div>
        </div>
    </div>
</body>
</html>